name: "NOTICE file generator"
description: "Generates NOTICE files"
runs:
  main: dist/index.mjs
  using: node20
branding:
  icon: "file-text"
  color: white
inputs:
  token:
    description: "GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)"
    default: ${{ github.token }}
  format:
    description: >
      The output format to use.
      Can be:
        - html
        - json
        - template
        - text
    default: "text"
  filename:
    description: ""
    default: "NOTICE"
outputs:
  notice-file-path:
    description: "Path to the generated NOTICE file"
  notice-filename:
    description: "Name of the generated NOTICE file"
