name: build

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          lfs: true
          fetch-depth: 0

      - name: "Install pnpm"
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: latest

      - name: "Install Node.js 20"
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 20
          cache: 'pnpm'

      - name: "Install dependencies"
        run: pnpm install

      - name: "Lint"
        run: pnpm run lint

      - name: "Build"
        run: pnpm run build

      - name: "Publish"
        if: success() && github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # tag=v4.16.0