name: build

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true
          fetch-depth: 0

      - name: "Install pnpm"
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: latest

      - name: "Install Node.js 20"
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install

      - name: "Lint"
        run: pnpm run lint

      - name: "Build"
        run: pnpm run build

      - name: "Publish"
        if: success() && github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
